### ISSUE TITLE
OriginalFPSParentSelectionMethod doesn't use cumulative weights

### ISSUE THREAD

**Issue by fergus-dall** [a1722797/EC2017#10]
When FPSP calculates the probability of acceptance, it does `weight[i] = population.get(i).getFitness() / sumOfFitness`. This needs to be cumulative, otherwise it's not actually picking individuals at a rate proportional to fitness.

**Comment by YanShuo1992** [comment]
The index is random.  So the weight doesn't need to be cumulative.

发自我的 iPhone

**Comment by fergus-dall** [comment]
Oh, I see what you're doing now. Does it matter that the number of parents chosen is only a fraction of the total population?

**Comment by YanShuo1992** [comment]
I am not sure about that.  However, I find somewhere that the number of offspring should be 7 times of parents traditionally and 3 times is popular these days.

发自我的 iPhone

**Comment by fergus-dall** [comment]
I think that's supposed to be 7 times the size of the parent population, however many parents are chosen.
