### ISSUE TITLE
Crossover operations should create two children

### ISSUE THREAD

**Issue by fergus-dall** [a1722797/EC2017#3]
All the descriptions given in the lecture slides about crossover operations imply that each operation creates two children. Currently the interface for crossover operations only allows for returning a single child. Do we want to change this?

EDIT: Except Edge Recombination.

EDIT2: See the new branch I just pushed

**Comment by a1722797** [comment]
I'd probably just have it return a list of children so you can return however many you want and the API user doesn't need to create a bunch of empty lists, but whatever works. Just remember to also update anything that uses the interface so it doesn't break.

**Comment by fergus-dall** [comment]
Oh, that's a much better idea. Works for Edge Recombination too.
