### ISSUE TITLE
CrossOverEdgeRecom edgeTable issue

### ISSUE THREAD

**Issue by a1722797** [a1722797/EC2017#9]
For some reason the following code exhausts the edgeTable 1 entry short of completion.
Can't see any obvious reason for the error, but it's crashing on the eil101 dataset.

Line 44-55
```
        while (child.size() < parentA.size()) {
            child.add(current);

            // Remove current symbol from edge table
            for (Symbol key : edgeTable.keySet()) {
                while (edgeTable.get(key).remove(current)) {
                }
            }

            Symbol next = pickNext(edgeTable, current);
            edgeTable.remove(current);
            current = next;
        }
```

**Comment by a1722797** [comment]
I think the code is good, but sometimes we're getting cities with one extra or less symbol than required.
Not sure if this is a factor of the crossover output, mutator output, or random population generation. I suspect it's not the mutator since this seems to consistently fail.

**Comment by fergus-dall** [comment]
All the cross over operators should work now, and be pretty quick except for EdgeRecomb.

The issue with EdgeRecomb was that under some circumstances it was forced to pick a new Symbol at random, and didn't remove the Symbol that had just been added from consideration before doing this.

**Comment by YanShuo1992** [comment]
The PMX only takes 1/10 time!

发自我的 iPhone
